[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "boto3~=1.40.6",
    "botocore~=1.40.6",
    "fastapi[standard]~=0.116.1",
    "mangum~=0.19.0",
    "passlib[bcrypt]~=1.7.4",
    "pydantic[email]~=2.11.7",
    "pydantic-settings~=2.1.0",
    "python-decouple~=3.8",
    "python-jose[cryptography]~=3.3.0",
    "python-multipart~=0.0.6",
    "requests~=2.32.4",
    "uvicorn[standard]~=0.24.0",
]
